# Generated by Django 3.0.4 on 2021-09-09 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the category', max_length=50, verbose_name='Name')),
                ('parent', models.ForeignKey(blank=True, default=None, help_text='For example cloth have three parents. Men, Women and Children', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='products.Category', verbose_name='Parent')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('%', '% (Percent)'), ('$', '$ (Toomaan)')], help_text='Type of the discount (percent% or amount$)', max_length=1, verbose_name='Type')),
                ('name', models.CharField(blank=True, default=None, help_text='Name of the discount', max_length=50, null=True, verbose_name='Name')),
                ('amount', models.PositiveIntegerField(help_text='Input positive amount', verbose_name='Discount Amount')),
            ],
            options={
                'verbose_name': 'Discount',
                'verbose_name_plural': 'Discounts',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the product', max_length=50, verbose_name='Name')),
                ('price', models.PositiveIntegerField(help_text='Input positive amount in Toomaan/1000', verbose_name='Price')),
                ('leftovers', models.PositiveIntegerField(help_text='Input positive amount', verbose_name='Leftovers')),
                ('sold', models.PositiveIntegerField(default=0, verbose_name='Sold items')),
                ('description', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='Description')),
                ('image', models.FileField(blank=True, default=None, help_text='Image of the product', null=True, upload_to='ProductImages/', verbose_name='Image')),
                ('color', models.CharField(help_text='Color of the product', max_length=30, verbose_name='Color')),
                ('size', models.CharField(blank=True, default=None, help_text="Size of the product (If it has'nt size, DO NOT fill it)", max_length=30, null=True, verbose_name='Size')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.Category', verbose_name='Category')),
                ('discount', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.Discount', verbose_name='Discount')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['category'],
            },
        ),
    ]
